{ lib }:

# Custom library functions for your NixOS configuration
# Generated by pam - you can add your own functions here
# Documentation: https://github.com/yourusername/pam

{
  # Package module generator used by pam-generated modules
  mkApp = import ./mkApp.nix { inherit lib; };

  # Add your custom helper functions below:
  # myFunction = ...;
}
